config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Root
  root 'hotels#index'
  get 'hotels/:id/rooms', to: 'hotels#rooms', as: 'hotel_rooms'
  get 'search', to: 'hotels#search'
  get '/bookings/index', to: 'bookings#index', as: 'bookings_index'

  # Definig the routes for the admin
  get 'admins/pending_bookings', to: 'admins#pending_bookings'
  get 'admins/confirmed_bookings', to: 'admins#confirmed_bookings'

  # Defines the route for approving and rejecting bookings
  get 'admins/approve_booking/:id', to: 'admins#approve_booking', as: 'approve_booking'
  get 'admins/reject_booking/:id', to: 'admins#reject_booking', as: 'reject_booking'

  match 'admins/approve_booking/:id', to: 'admins#approve_booking', via: %i[get patch]
  match 'admins/reject_booking/:id', to: 'admins#reject_booking', via: %i[get patch]

  patch 'admins/approve_booking/:id', to: 'admins#approve_booking'
  patch 'admins/reject_booking/:id', to: 'admins#reject_booking'

  # users authentication
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'


  # Resources
  resources :hotels
  resources :roomtypes
  resources :rooms

  resources :rooms do
    resources :bookings, only: %i[new create]
  end
end

app/controllers/roomtypes_controller.rb
# frozen_string_literal: true

class RoomtypesController < ApplicationController
  before_action :require_admin, only: %i[index new create edit update destroy]

  def index
    @roomtypes = Roomtype.all
  end

  def show
    @roomtype = Roomtype.find(params[:id])
  end

  def new
    @hotels = Hotel.all
    @roomtype = Roomtype.new
  end

  def create
    @hotels = Hotel.all
    @roomtype = Roomtype.new(roomtype_params)
    if @roomtype.save
      flash[:success] = 'Roomtype created successfully'
      redirect_to @roomtype
    else
      render 'new'
    end
  end

  def edit
    @roomtype = Roomtype.find(params[:id])
  end

  def update
    @roomtype = Roomtype.find(params[:id])
    if @roomtype.update(roomtype_params)
      flash[:success] = 'Roomtype updated successfully'
      redirect_to @roomtype
    else
      flash.now[:danger] = 'Roomtype was not updated'
      render 'edit'
    end
  end

  def destroy
    @roomtype = Roomtype.find(params[:id])
    @roomtype.destroy
    redirect_to roomtypes_path
    flash[:danger] = 'Roomtype deleted successfully'
  end

  private

  def roomtype_params
    params.require(:roomtype).permit(:roomtypename, :description)
  end
end

app/helpers/roomtypes_helper.rb
# frozen_string_literal: true

module RoomtypesHelper
end

app/views/roomtypes/_form.html.erb
<%= render "shared/errors", obj: @roomtype %>
<%= form_with model: @roomtype do |form| %>


    <div class="mt-3">
        <%= form.label :roomtype %><br>
        <%= form.text_field :roomtypename , class: 'form-control', required: true %>
    </div>

    
    <div class="mt-2">
        <%= form.label :description %><br>
        <%= form.text_area :description , class: 'form-control', required: true %>
    </div>

    <div class="my-3">
        <%= form.submit class: "btn btn-primary btn-block" %>
    </div>
<% end %>

app/views/roomtypes/edit.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 border shadow p-3 mb-5 bg-white rounded my-5">
<h3 class="my-4 d-flex justify-content-center">Edit Roomtype</h3>

<%= render "roomtypes/form" %>
</div>
</div>

app/views/roomtypes/index.html.erb
<div class="container">
<% @roomtypes.each do |roomtype| %>

<div class="card-container my-4">
  <h5><%= roomtype.roomtypename %></h5>
  <div class="card-body text-primary ">
    <h5 class="card-title">About this Roomtype</h5>
    <p class="card-text"><%= roomtype.description %></p>
  </div>
    <div class="border-top pt-3">
        <%= link_to "Edit Roomtype", edit_roomtype_path(roomtype), class: "mr-4" %>
        <%= link_to "Delete Roomtype", roomtype_path(roomtype), method: :delete, data: { confirm: "Are you sure?" }, class: "text-danger" %>
    </div>
</div>
<% end %>
</div>

app/views/roomtypes/new.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 border shadow p-3 mb-5 bg-white rounded my-5">
<h3 class="my-4 d-flex justify-content-center">New Roomtype</h3>

<%= render "roomtypes/form" %>
</div>
</div>

app/views/roomtypes/show.html.erb
<div class="container">
<div class="card-container my-4">
  <h5><%= @roomtype.roomtypename %></h5>
    <div class="card-body text-primary ">
      <h5 class="card-title">About this Roomtype</h5>
      <p class="card-text"><%= @roomtype.description %></p>
    </div>
    <div class="border-top" >
      <%= link_to"Back",roomtypes_path %>
    </div>
</div>
</div>