config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Root
  root 'hotels#index'
  get 'hotels/:id/rooms', to: 'hotels#rooms', as: 'hotel_rooms'
  get 'search', to: 'hotels#search'
  get '/bookings/index', to: 'bookings#index', as: 'bookings_index'

  # Definig the routes for the admin
  get 'admins/pending_bookings', to: 'admins#pending_bookings'
  get 'admins/confirmed_bookings', to: 'admins#confirmed_bookings'

  # Defines the route for approving and rejecting bookings
  get 'admins/approve_booking/:id', to: 'admins#approve_booking', as: 'approve_booking'
  get 'admins/reject_booking/:id', to: 'admins#reject_booking', as: 'reject_booking'

  match 'admins/approve_booking/:id', to: 'admins#approve_booking', via: %i[get patch]
  match 'admins/reject_booking/:id', to: 'admins#reject_booking', via: %i[get patch]

  patch 'admins/approve_booking/:id', to: 'admins#approve_booking'
  patch 'admins/reject_booking/:id', to: 'admins#reject_booking'

  # users authentication
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'


  # Resources
  resources :hotels
  resources :roomtypes
  resources :rooms

  resources :rooms do
    resources :bookings, only: %i[new create]
  end
end

app/views/admins/confirmed_bookings.html.erb
    <div class="row">
        <div class="col-md-12 my-5 border rounded shadow">
        <h3 class="my-4 text-center">Confirmed Bookings</h3>
        <table class="table table-striped">
            <thead>
            <tr>
               
                <th>Name</th>
                <th>email</th>
                <th>Phone No. </th>
                <th>Hotel Name</th>
                <th>Room Type</th>
                <th>Check In</th>
                <th>Check Out</th>
                <th>Guests</th>
                <th>Rooms</th>
            </tr>
            </thead>
            <tbody>
            <% @bookings.each do |booking| %>
                <tr>
                <td><%= booking.guestname %></td>
                <td><%= booking.user.email %></td>
                <td><%= booking.phone %></td>
                <td><%= booking.room.hotel.hotelname %></td>
                <td><%= booking.room.roomtype.roomtypename %></td>
                <td><%= booking.start_date %></td>
                <td><%= booking.end_date %></td>
                <td class="text-center"><%= booking.guests %></td>
                <td class="text-center"><%= booking.number_of_room %></td>
                </tr>
            <% end %>
            </tbody>
        </table>
        
        </div>
        
    </div>
    <div class="d-flex mb-4" style="justify-content: center; align-item: center">
        <%= paginate @bookings %>
    </div>

app/views/admins/pending_bookings.html.erb
<% if @bookings.count == 0 %>
<div class="container border shadow rounded my-5">
    <h3 class="my-4 text-center">No new bookings pending for approval </h3>
</div>

<% else %>
<div class="border shadow rounded my-5">
    <div class="row">
        <div class="col-md-12">
        <h3 class="my-4 text-center">Pending Bookings</h3>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Phone No. </th>
                <th>Hotel Name</th>
                <th>Room Type</th>
                <th>Check In</th>
                <th>Check Out</th>
                <th>Guests</th>
                <th>Rooms</th>
                <th>Booking Action</th>
            </tr>
            </thead>
            <tbody>
            <% @bookings.each do |booking| %>
                <tr>
                <td><%= booking.guestname %></td>
                <td><%= booking.phone %></td>
                <td><%= booking.room.hotel.hotelname %></td>
                <td><%= booking.room.roomtype.roomtypename %></td>
                <td><%= booking.start_date %></td>
                <td><%= booking.end_date %></td>
                <td class="text-center"><%= booking.guests %></td>
                <td class="text-center"><%= booking.number_of_room %></td>
                <td>
                <%= link_to "Accept", approve_booking_path(booking.id), class:"btn btn-success" %>
                <%= link_to "Reject", reject_booking_path(booking.id), class:"btn btn-danger" %>
                </td> 
                </tr>
            <% end %>
            </tbody>
        </table>
        </div>
    </div>
    <div class="d-flex mb-4" style="justify-content: center; align-item: center">
        <%= paginate @bookings %>
    </div>
</div>
<% end %>