config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Root
  root 'hotels#index'
  get 'hotels/:id/rooms', to: 'hotels#rooms', as: 'hotel_rooms'
  get 'search', to: 'hotels#search'
  get '/bookings/index', to: 'bookings#index', as: 'bookings_index'

  # Definig the routes for the admin
  get 'admins/pending_bookings', to: 'admins#pending_bookings'
  get 'admins/confirmed_bookings', to: 'admins#confirmed_bookings'

  # Defines the route for approving and rejecting bookings
  get 'admins/approve_booking/:id', to: 'admins#approve_booking', as: 'approve_booking'
  get 'admins/reject_booking/:id', to: 'admins#reject_booking', as: 'reject_booking'

  match 'admins/approve_booking/:id', to: 'admins#approve_booking', via: %i[get patch]
  match 'admins/reject_booking/:id', to: 'admins#reject_booking', via: %i[get patch]

  patch 'admins/approve_booking/:id', to: 'admins#approve_booking'
  patch 'admins/reject_booking/:id', to: 'admins#reject_booking'

  # users authentication
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'


  # Resources
  resources :hotels
  resources :roomtypes
  resources :rooms

  resources :rooms do
    resources :bookings, only: %i[new create]
  end
end

app/views/shared/_commonroomview.html.erb
 <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%= @hotel.latitude%>, <%= @hotel.longitude%>);
    });
  </script>


<% @rooms.each do |room| %>

<div class="hotel-index border shadow bg-white rounded my-5">

<div class="card ml-4 my-4" style="width: 50rem">
        <% if room.image.attached? %>
            <img class="card-img-top" src=" <%= (url_for(room.image)) %> " alt="Card image cap">
        <% end %>
</div>

<div class="card-body border-right">

    
    <div class="icon-wrap">
    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24"> <g> <path fill="none" d="M0 0h24v24H0z"/> <path d="M22 11v9h-2v-3H4v3H2V4h2v10h8V7h6a4 4 0 0 1 4 4zM8 13a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/> </g> </svg> 
    <span class="font-weight-bold text-primary"><%= room.roomtype.roomtypename  %></span>
    </div>

    <div class="icon-wrap d-flex">
        <span class="mt-1 material-symbols-outlined">currency_rupee</span>
        <span class="pl-1 mt-1 text-primary"><%= room.price %>/- <small> per night </small></span>
    </div>
    <p class="my-3"><%= room.roomtype.description %></p> 

   
    <% if room.roomtype.roomtypename == "Luxury Suite" %>
   
    <div class="icon-wrap d-flex">
    <span class="material-symbols-outlined">wifi</span>
    <span class="pl-1 pb-2 text-primary">Free Wifi</span>

    <span class="pl-3 material-symbols-outlined">pool</span>
    <span class="pl-1 text-primary">Swimming pool</span>

    <span class="pl-3 material-symbols-outlined">kitchen</span>
    <span class="pl-1 text-primary">Kitchen</span>

    </div>

    <% elsif room.roomtype.roomtypename == "President Suite" %>
    <div class="icon-wrap d-flex">
    <span class="material-symbols-outlined">wifi</span>
    <span class="pl-1 pb-2 text-primary">Free Wifi</span>

    <span class="pl-3 material-symbols-outlined">pool</span>
    <span class="pl-1 text-primary"> Swimming pool</span>

    <span class="pl-3 material-symbols-outlined">bathtub</span>
    <span class="pl-1 text-primary">Bathtub</span>

    <span class="pl-3 material-symbols-outlined">spa</span>
    <span class="pl-1 text-primary">Spa</span>

    <span class="pl-3 material-symbols-outlined">local_bar</span>
    <span class="pl-1 text-primary">Bar</span>

    </div>

    <% else %>
    <div class="icon-wrap d-flex">
    <span class="material-symbols-outlined">wifi</span>
    <span class="pl-1 pb-2 text-primary">Free Wifi</span>

    <span class="material-symbols-outlined">tv</span>
    <span class="pl-1 text-primary">TV</span>

    <span class="material-symbols-outlined">elevator</span>
    <span class="pl-1 text-primary">Elevator</span>

    <% end %>
</div>

<div class="button-contianer p-3">

<% if logged_in? && current_user.is_admin? %>
    <%= link_to "Edit", edit_room_path(room.id), class: 'btn btn-primary mb-3' %>
    <%= link_to "Delete", room, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
<% else %>
    <%# <%= link_to "Book This Room", new_booking_path(room_id: room.id), class: 'btn btn-primary' %>
    <%= link_to "Book This Now",new_room_booking_path(room.id), class: 'btn btn-primary mb-3'  %>
<% end %>
</div>
</div>
    

<% end %>
</div>

<div id="map" class="my-3" style="width: 58%; height: 250px; position:relative; left: 25rem"></div>
</div>

app/views/shared/_errors.html.erb
 
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h6 class="alert-heading">The following errors prevented the <%= obj.class%> from being saved</h6>
        <ul>
            <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        </button>
    </div>   
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container d-flex text-center mb-4" style="position: relative; left: 25rem">
      <div class="about-us">
        <h4> Save Time, Save Money! </h4>
          <p>Sign up and we'll send the best deals to you. </p>
            <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="Email" aria-label="Recipient's username" aria-describedby="basic-addon2">
                <div class="input-group-append">
                  <button class="btn btn-outline-secondary" type="button">Subscribe</button>
              </div>
            </div>
      </div> 
  </div>
  
      <div class="text-center pt-4 border-top border-white">
        <h4>BOOKING.COM</h4>
        <small> Copyright 2022 BOOKING.COM | All rights reserved </small>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
<div class="container">
  <a class="navbar-brand" href="/">BOOKING.COM</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">

      <%# USER %>
      <% if !Current.user %>
      <li class="nav-item">
        <a class="login nav-link border rounded py-2 px-5" href="sign_in">SIGN IN</a>
      </li>
   

      <%# ADMIN %>
      <% elsif logged_in? && current_user.is_admin? %>
      <li class="nav-item dropdown bg-dark mr-4">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Hotel
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/hotels/new">Add New Hotel</a>
          <a class="dropdown-item" href="/hotels">View All Hotels</a>
        </div>
      </li>


       <li class="nav-item dropdown bg-dark mr-4">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Room
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/rooms/new">Add New Room</a>
          <a class="dropdown-item" href="/rooms">View All Rooms</a>
        </div>
       </li>


       <li class="nav-item dropdown bg-dark mr-4">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Roomtype
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/roomtypes/new">Add New Roomtype</a>
          <a class="dropdown-item" href="/roomtypes">View All Roomtypes</a>
        </div>
       </li>

        <li class="nav-item dropdown mr-4">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            All Bookings
          </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="/admins/pending_bookings">Pending for Approval</a>
              <a class="dropdown-item" href="/admins/confirmed_bookings">Confirmed Bookings</a>
            </div>
      </li>

        <li class="nav-item">
        <a class="nav-link"> <%= link_to 'LOGOUT', logout_path, method: :delete, data: {"turbo-method": :delete},style: 'position: relative; bottom: 0.5rem; margin-left: 10rem', class:"border rounded py-2 px-5" %></a>
      </li>
   

       
      <% else %>
       <li class="nav-item dropdown">
        <a class="login border rounded py-2 px-5 nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <%= Current.user.username.split('@')[0].upcase %> </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/bookings/index">My Bookings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" > <%= link_to 'Logout', logout_path, method: :delete, data: { "turbo-method": :delete},style: 'color: black; position: relative; left: 2.5rem; bottom: 0.5rem' %> </a>
        </div>
        </li>


      <% end %>

      
      
      
     
      
    </ul>
    
  </div>
  </div>
</nav>

app/views/shared/_searchform.html.erb
  

      <form action="/search" id="search">
      <div class="container">
        <div class="inner-form border rounded shadow-sm">
          <div class="input-field first-wrap">
            <div class="icon-wrap">
              <span class="material-symbols-outlined">pin_drop</span>
            </div>
             <input class="form-control mr-sm-2" required = true name ="q" type="search" placeholder="Enter a destination" aria-label="Search">

          </div>
          <div class="input-field second-wrap">
            <div class="icon-wrap">
              <span class="material-symbols-outlined">event</span>
            </div>
            <input class="datepicker"  id="booking_start" type="text" placeholder="Start date" />
          </div>
          <div class="input-field third-wrap">
            <div class="icon-wrap">
              <span class="material-symbols-outlined">event</span>
            </div>
            <input class="datepicker" id="booking_end" type="text" placeholder="End date" />
          </div>
          <div class="input-field fouth-wrap">
            <div class="icon-wrap">
             <span class="material-symbols-outlined">person</span>
            </div>
            <select data-trigger="" name="choices-single-default">
              <option placeholder="">1 Adults</option>
              <option>2 Adults</option>
              <option>3 Adults</option>
              <option>4 Adults</option>
              <option>5 Adults</option>
            </select>
          </div>

          <div class="input-field fifth-wrap">
            <button class="btn-search" type="submit">SEARCH</button>
          </div>
        </div>
        </div>
      </form>


    
   