config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Root
  root 'hotels#index'
  get 'hotels/:id/rooms', to: 'hotels#rooms', as: 'hotel_rooms'
  get 'search', to: 'hotels#search'
  get '/bookings/index', to: 'bookings#index', as: 'bookings_index'

  # Definig the routes for the admin
  get 'admins/pending_bookings', to: 'admins#pending_bookings'
  get 'admins/confirmed_bookings', to: 'admins#confirmed_bookings'

  # Defines the route for approving and rejecting bookings
  get 'admins/approve_booking/:id', to: 'admins#approve_booking', as: 'approve_booking'
  get 'admins/reject_booking/:id', to: 'admins#reject_booking', as: 'reject_booking'

  match 'admins/approve_booking/:id', to: 'admins#approve_booking', via: %i[get patch]
  match 'admins/reject_booking/:id', to: 'admins#reject_booking', via: %i[get patch]

  patch 'admins/approve_booking/:id', to: 'admins#approve_booking'
  patch 'admins/reject_booking/:id', to: 'admins#reject_booking'

  # users authentication
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'


  # Resources
  resources :hotels
  resources :roomtypes
  resources :rooms

  resources :rooms do
    resources :bookings, only: %i[new create]
  end
end

app/models/hotel.rb
# frozen_string_literal: true

class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
  has_many :roomtypes, through: :rooms

  has_one_attached :image

  validates :hotelname, presence: true, format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :about, presence: true
  validates :city, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/controllers/hotels_controller.rb
# frozen_string_literal: true

class HotelsController < ApplicationController
  before_action :require_admin, only: %i[new create edit update destroy]
  
  before_action :require_user_logged_in!, only: %i[rooms]
 
  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @rooms = @hotel.rooms
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)
    if @hotel.save
      flash[:success] = 'Hotel created successfully'
      redirect_to @hotel
    else
      render 'new'
    end
  end

  def edit
    @hotel = Hotel.find(params[:id])
  end

  def update
    @hotel = Hotel.find(params[:id])
    if @hotel.update(hotel_params)
      flash[:success] = 'Hotel updated successfully'
      redirect_to @hotel
    else
      flash.now[:danger] = 'Hotel was not updated'
      render 'edit'
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    redirect_to hotels_path
    flash[:danger] = 'Hotel deleted successfully'
  end

  def rooms
    @hotel = Hotel.find(params[:id])
    @rooms = @hotel.rooms
  end

  def search
    @hotels = Hotel.where('city LIKE ?', "%#{params[:q]}%")
  end

  private

  def hotel_params
    params.require(:hotel).permit(:hotelname, :city, :address, :about, :latitude, :longitude, :image)
  end
end

app/helpers/hotels_helper.rb
# frozen_string_literal: true

module HotelsHelper
end

app/views/hotels/_form.html.erb
<%= render "shared/errors", obj: @hotel %>

<%= form_with model: @hotel do |form| %>


<div class="container">
  <div class="mt-3">
    <%= form.label :hotel_name %><br>
    <%= form.text_field :hotelname , class: 'form-control', required: true %>
  </div>

  <div class="mt-2">
    <%= form.label :about %><br>
    <%= form.text_area :about , class: 'form-control', required: true %>
  </div>

  
   <div class="mt-2">
    <%= form.label :city %><br>
    <%= form.text_field :city , class: 'form-control', required: true %>
  </div>

  <div class="mt-2">
    <%= form.label :address %><br>
    <%= form.text_field :address , class: 'form-control', required: true %>
  </div>

  <div class="mt-2">
    <%= form.label :longitude %><br>
    <%= form.text_field :longitude , class: 'form-control', required: true %>
  </div>

  <div class="mt-2">
    <%= form.label :latitude %><br>
    <%= form.text_field :latitude , class: 'form-control' , required: true %>
  </div>

  

  <div class="form-group mt-3">
  <% if @hotel.image.attached? %>
    <%= image_tag @hotel.image, style: "width: 200px; display: block" %>
  <% end %>
  <%= form.label :image %><br>
  <%= form.file_field :image, class: "form-control" %>
  </div>

  <div class="my-3">
    <%= form.submit class: "btn btn-primary btn-block" %>
  </div>
  
</div>
  
<% end %>

app/views/hotels/edit.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 border shadow p-3 mb-5 bg-white rounded my-5">
    <h3 class="my-4 d-flex justify-content-center">Edit Hotel</h3>
    <%= render "hotels/form" %>
</div>
</div>

app/views/hotels/index.html.erb
<div class="s002 py-5 mt-3"> 

    <%= render "shared/searchform" %> 

</div> 

<% @hotels.each do |hotel| %>
<div class="container">
<div class="hotel-index border shadow rounded mt-3 mb-5">

    <div class="card ml-4 my-4" style="width: 23rem;">
        <% if hotel.image.attached? %>
            <img class="card-img-top" src=" <%= (url_for(hotel.image)) %> " alt="Card image cap">
        <% end %>
    </div>

    <div class="card-body border-right">
        <h5 class="font-weight-bold text-primary"><%= hotel.hotelname  %></h5>
        <div class="icon-wrap d-flex">
        <span class="material-symbols-outlined">location_on</span>
        <span class="pl-1 text-primary"><%= hotel.city %></span>
        </div>
    
        <p class="pt-1"><%= hotel.about %></p> 
         <div class="d-flex">
            <% hotel.rooms.each do |room| %>
               <p class="text-primary mr-4"> <%= room.roomtype.roomtypename %>  <%= room.total_rooms %> avaliable</p>
            <% end %>
        </div>
        
    </div>  

    <div class="button-contianer px-3 py-3">
    <% if logged_in? && current_user.is_admin? %>
    <%= link_to "Edit Hotel", edit_hotel_path(hotel.id), class: "btn btn-primary mb-3" %>
    <%= link_to "Delete Hotel", hotel_path(hotel), :method => :delete, data:{confirm: "Are You Sure?" },class:"btn btn-danger"%>
       
    <% elsif  hotel.rooms.count != 0%>
    <%= link_to "View Rooms", hotel_rooms_path(hotel), class:"btn btn-primary"%>
    <% else %>
    <p><b> (&nbsp No Rooms avaliable for booking &nbsp) </b></p>
    
    <% end %>
    </div>



</div>
</div>
    

<% end %>

app/views/hotels/new.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 border shadow p-3 mb-5 bg-white rounded my-5">
    <h3 class="my-4 d-flex justify-content-center">New Hotel</h3>

    <%= render "hotels/form" %>
</div>
</div>

app/views/hotels/rooms.html.erb
 <meta name='turbolinks-visit-control' content='reload'>
  <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(<%= @hotel.latitude%>, <%= @hotel.longitude%>);
    });
  </script>
<div class="container">
<% @rooms.each do |room| %>
<% if room.total_rooms != 0 %>

  <div class="hotel-index border shadow rounded my-5">
    <div class="card ml-4 my-4" style="width: 21rem">
        <% if room.image.attached? %>
            <img class="card-img-top" src=" <%= (url_for(room.image)) %> " alt="Card image cap">
        <% end %>
    </div>
    <div class="card-body border-right">
        <div class="icon-wrap mb-4">
            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24"> <g> <path fill="none" d="M0 0h24v24H0z"/> <path d="M22 11v9h-2v-3H4v3H2V4h2v10h8V7h6a4 4 0 0 1 4 4zM8 13a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"/> </g> </svg> 
            <span class="font-weight-bold text-primary"><%= room.roomtype.roomtypename  %></span>
            <span class="mt-1 ml-5 text-primary border rounde shadow border-success p-3"><%= room.price %>/- <small> per night </small></span>
        </div>
        <p class="my-3"><%= room.roomtype.description %></p> 
    <% if room.roomtype.roomtypename == "Luxury Suite" %>
       
    <div class="icon-wrap d-flex">
        <span class="material-symbols-outlined">wifi</span>
        <span class="pl-1 pb-2 text-primary">Free Wifi</span>

        <span class="pl-3 material-symbols-outlined">pool</span>
        <span class="pl-1 text-primary">Swimming pool</span>

        <span class="pl-3 material-symbols-outlined">kitchen</span>
        <span class="pl-1 text-primary">Kitchen</span>
        
    </div>
     <% if room.total_rooms < 7 %>
        <marquee> <span class="text-danger p-2">Rooms are filling fast, Only <%= room.total_rooms %> rooms left </span> </marquee>
    <% end %>

    <% elsif room.roomtype.roomtypename == "President Suite" %>
    <div class="icon-wrap d-flex">
    <span class="material-symbols-outlined">wifi</span>
    <span class="pl-1 pb-2 text-primary">Free Wifi</span>

    <span class="pl-3 material-symbols-outlined">pool</span>
    <span class="pl-1 text-primary"> Swimming pool</span>

    <span class="pl-3 material-symbols-outlined">bathtub</span>
    <span class="pl-1 text-primary">Bathtub</span>

    <span class="pl-3 material-symbols-outlined">spa</span>
    <span class="pl-1 text-primary">Spa</span>

    <span class="pl-3 material-symbols-outlined">local_bar</span>
    <span class="pl-1 text-primary">Bar</span>
    </div>
     <% if room.total_rooms < 5 %>
        <marquee> <span class="text-danger p-2">Rooms are filling fast, Only <%= room.total_rooms %> rooms left </span> </marquee>
    <% end %>
    
    <% else %>

    <div class="icon-wrap d-flex">
    <span class="material-symbols-outlined">wifi</span>
    <span class="pl-1 pb-2 text-primary">Free Wifi</span>

    <span class="pl-3 material-symbols-outlined">tv</span>
    <span class="pl-1 text-primary">TV</span>

    <span class="pl-3 material-symbols-outlined">elevator</span>
    <span class="pl-1 text-primary">Elevator</span>
    </div>

     <% if room.total_rooms < 7 %>
        <marquee> <span class="text-danger p-2">Rooms are filling fast, Only <%= room.total_rooms %> rooms left </span> </marquee>
    <% end %>

    <% end %>
    
</div>

    <div class="button-contianer p-3">
        <% if logged_in? && current_user.is_admin? %>

        <%= link_to "Edit", edit_room_path(room.id), class: 'btn btn-primary mb-3' %>
        <%= link_to "Delete", room, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>

        <% else %>
        <%= link_to "Book This Now",new_room_booking_path(room.id), class: 'btn btn-primary mb-3'  %>
        <% end %>
    </div>
</div>
<% end %>
<% end %>

</div>  
</div>
</div>
<div id="map" class=" container my-3" style="width: 73%; height: 250px; position:relative"></div>

app/views/hotels/search.html.erb
<div class="container">
<% if @hotels.count != 0 %>
<% @hotels.each do |hotel| %>

<div class="hotel-index border shadow bg-white rounded my-5">

<div class="card ml-4 my-4" style="width: 20rem">
        <% if hotel.image.attached? %>
            <img class="card-img-top" src=" <%= (url_for(hotel.image)) %> " alt="Card image cap">
        <% end %>
</div>

<div class="card-body border-right">
    <h5 class="font-weight-bold text-primary"><%= hotel.hotelname  %></h5>
     <div class="icon-wrap d-flex">
        <span class="material-symbols-outlined">location_on</span>
        <span class="pl-1 text-primary"><%= hotel.city %></span>
    </div>
    
    <p class="py-2"><%= hotel.about %></p> 
    <div class="d-flex">
        
        <% hotel.rooms.each do |room| %>
           <p class="text-primary"> <%= room.roomtype.roomtypename %>  <%= room.total_rooms %> avaliable</p>
        <% end %>  
    </div>
</div>


<div class="button-contianer p-3">
    <% if logged_in? && current_user.is_admin? %>

    
    <%= link_to "Edit Hotel", edit_hotel_path(hotel.id), class: "btn btn-primary mb-3" %>
    <%# <%= link_to "Add Rooms", new_hotel_room_path(hotel), class:"btn btn-primary", style:"position: relative; left: 10rem" %>
    <%= link_to "Delete Hotel", hotel_path(hotel), :method => :delete, data:{confirm: "Are You Sure?" },class:"btn btn-danger"%>

    <% elsif %>

    <%  hotel.rooms.count != 0%>
     <%= link_to "View Rooms", hotel_rooms_path(hotel), class:"btn btn-primary"%>

    <% else %>
    <p><b> (&nbsp No Rooms avaliable for booking &nbsp) </b></p>
    
    <% end %>
</div>


</div>
</div>


<% end %>
<% else %>
<div class="container mt-5">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h1 class="display-5">No Hotels Found</h1>
                <p class="lead">Sorry, we couldn't find any hotels matching your search.</p>
                <hr class="my-4">
                <p>Try searching again with different keywords.</p>
                <p class="lead">
                    <%= link_to "Home", root_path, class: "btn btn-primary" %>
                </p>
            </div>
        </div>
    </div>
</div>
</div>
<% end %>

app/views/hotels/show.html.erb
<div class="container">
<div class="hotel-index border shadow bg-white rounded my-5">

    <div class="card ml-4 my-4" style="width: 20rem">
        <% if @hotel.image.attached? %>
            <img class="card-img-top" src=" <%= (url_for(@hotel.image)) %> " alt="Card image cap">
        <% end %>
    </div>

    <div class="card-body">
        <h5 class="font-weight-bold text-primary"><%= @hotel.hotelname  %></h5>
            <div class="icon-wrap">
                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24">
                <path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"></path>
                </svg>
                <span class="text-primary"><b> <%= @hotel.city %> </b></span>
            </div>
    
        <p class="py-4"><%= @hotel.about %></p> 
    
    </div>
    </div>
    </div>
   